// frontend/src/lib/Header.svelte
<script lang="ts">
  import logo from "$lib/assets/logo.svg";
</script>

<nav class="flex w-full flex-grow-0 items-center justify-start px-2 sm:py-2">
  <img alt="AtCoder Logo" src={logo} class="mx-2 my-1 aspect-square h-8 rounded-full bg-white sm:m-2 sm:h-12" />
  <a href="/" class="font-roboto my-2 block text-xl font-medium text-gray-700"> AtCoder Search </a>
</nav>

// frontend/app/components/Header.tsx
import { Link } from "@remix-run/react";

export default function Header() {
  return (
    <div className="flex flex-row w-full items-center gap-2 px-2 py-1 justify-start">
      <img
        alt="AtCoder Search Logo"
        src="/logo.svg"
        className="aspect-square h-6 rounded-full select-none"
      />
      <Link to="/" className="text-xl font-medium select-none">
        AtCoder Search
      </Link>
    </div>
  );
}
