// frontend/app/routes/problem.tsx
import { useLoaderData, json, Form } from "@remix-run/react";
import { useState } from "react";
import { client } from "~/client";

export const loader = async () => {
  const { data, error } = await client.POST("/api/problem", {
    body: {
      facet: ["category", "difficulty"],
    },
  });

  if (error != null) {
    throw new Response("request failed", {
      status: 500,
      statusText: "INTERNAL SERVER ERROR",
    });
  }

  return json(data);
};

export default function ProblemPage() {
  const data = useLoaderData<typeof loader>();
  const [menuOpen, setMenuOpen] = useState(false);
  const [lastSelected, setLastSelected] = useState("");

  const categories = data.facet.category ?? [];
  const difficulties = data.facet.difficulty ?? [];

  const toggle = () => {
    setMenuOpen(!menuOpen);
  };

  return (
    <>
      <div className="flex flex-row justify-between lg:justify-end items-center py-2 px-2">
        <button
          type="button"
          className={`lg:hidden rounded-xl px-3 py-1 border shadow-sm shadow-gray-500 ${
            menuOpen ? "bg-gray-200 dark:bg-gray-950 dark:text-gray-400" : ""
          }`}
          onClick={toggle}
        >
          絞り込み
        </button>
        <span>
          約{data.total}件 / {data.time}ms
        </span>
      </div>

      <div className="lg:flex lg:flex-row">
        <div
          className={`${
            menuOpen ? "block" : "hidden"
          } lg:block absolute lg:static w-5/6 lg:w-1/4 bg-white dark:bg-gray-950 px-4 py-2 shadow-md shadow-gray-500 rounded-xl`}
        >
          <Form method="GET">
            <div className="flex flex-row items-center justify-between text-lg">
              <span className="text-lg font-bold">絞り込み</span>
              <button type="button" className="lg:hidden" onClick={toggle}>
                ✗
              </button>
            </div>

            <div className="flex flex-col gap-3">
              <label className="block">
                <span className="block text-lg">キーワード</span>
                <input
                  type="text"
                  name="q"
                  className="border rounded-md border-gray-400 shadow-sm"
                />
              </label>

              <div>
                <p className="text-lg">カテゴリ</p>
                <div className="flex flex-wrap gap-0.5">
                  {categories.map((c) => (
                    <label key={c.label} className="block p-0.5 select-none">
                      <input
                        type="checkbox"
                        name="category"
                        className="mr-1"
                        value={c.label}
                      />
                      <span className="">
                        {c.label}({c.count})
                      </span>
                    </label>
                  ))}
                </div>
              </div>

              <div>
                <p className="text-lg">難易度</p>
                <div className="flex flex-wrap gap-0.5">
                  {difficulties.map((c) => (
                    <label key={c.label} className="block p-0.5 select-none">
                      <input
                        type="radio"
                        id={c.label}
                        name="difficulty"
                        className="mr-1"
                        value={c.label.replaceAll(" ", "").replaceAll("~", "-")}
                        onClick={(e) => {
                          if (e.currentTarget.id === lastSelected) {
                            e.currentTarget.checked = !e.currentTarget.checked;
                            setLastSelected("");
                          } else {
                            setLastSelected(e.currentTarget.id);
                          }
                        }}
                      />
                      <span className="">
                        {c.label}({c.count})
                      </span>
                    </label>
                  ))}
                </div>
              </div>

              <div>
                <p className="text-lg">その他</p>

                <div className="flex flex-col gap-2">
                  <label className="block">
                    <span className="block">解いたことのある問題を除外</span>
                    <input
                      type="text"
                      placeholder="ユーザID"
                      name="userId"
                      className="border rounded-md border-gray-400 shadow-sm px-2"
                    />
                  </label>

                  <label className="block">
                    <input
                      type="checkbox"
                      name="isExperimental"
                      className="mr-1"
                    />
                    <span>試験管問題を除外</span>
                  </label>
                </div>
              </div>
            </div>

            <div className="flex flex-row items-center justify-end">
              <button
                type="submit"
                className="px-3 py-2 rounded-lg bg-blue-600 text-gray-100"
              >
                絞り込む
              </button>
            </div>
          </Form>
        </div>

        <div className="flex flex-col lg:flex-grow items-center px-2 text-sm gap-1 py-1">
          {data.items.map((item) => (
            <div
              key={item.problemId}
              className="border rounded-md min-w-60 max-w-xl w-full py-2 flex flex-row items-center justify-between gap-2 px-2"
            >
              <a href={item.contestUrl} className="text-center">
                {item.contestId}
              </a>
              <a href={item.problemUrl} className="text-balance text-center">
                {item.problemTitle}
              </a>
              <span className="min-w-8">{item.difficulty}</span>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}

// frontend/src/routes/problem/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { page } from "$app/stores";
  import Header from "$lib/Header.svelte";
  import SearchBar from "$lib/SearchBar.svelte";
  import Tab from "$lib/Tab.svelte";
  import { bgColorStyles, textColorStyles } from "$lib/colors";
  import type { SearchProblemResult } from "$lib/response";
  import { createQuery } from "@tanstack/svelte-query";
  import dayjs from "dayjs";
  import timezone from "dayjs/plugin/timezone";
  import utc from "dayjs/plugin/utc";
  import FilterMenu from "./FilterMenu.svelte";
  import { fetchSearchProblemResult } from "./query";
  import { selections } from "./sort";

  dayjs.extend(timezone);
  dayjs.extend(utc);

  $: width = 0;
  const widthThreshold = 768;

  let opened = false;
  let detail: string | null = null;
  let s: string = $page.url.searchParams.get("s") ?? "2";

  export let data: SearchProblemResult;
  const searchQuery = createQuery({
    queryKey: ["search"],
    queryFn: async () => {
      const res = await fetchSearchProblemResult($page.url.searchParams, fetch);
      return res;
    },
    initialData: data,
  });

  function convertDateTime(date: string): string {
    return dayjs(date).tz("Asia/Tokyo").format("YYYY/MM/DD HH:mm:ss");
  }
</script>

<svelte:window bind:outerWidth={width} />

<div class="flex h-dvh flex-col bg-gray-100">
  <Header />
  <Tab selected={"problem"} />

  <div class={`flex ${width > widthThreshold ? "flex-row justify-between" : "flex-col"}`}>
    <div class="mx-2 my-1">
      <label class={`block select-none rounded-md py-2 text-center font-semibold shadow-sm shadow-gray-500 ` + (opened ? "bg-blue-500 text-gray-50" : "text-gray-800")}>
        絞り込み
        <input
          type="button"
          class="hidden"
          on:click={() => {
            if (width > widthThreshold) {
              opened = true;
            } else {
              opened = !opened;
            }
          }}
        />
      </label>
      {#if $searchQuery.isLoading}
        <p>Loading...</p>
      {:else if $searchQuery.isError}
        <p>ERROR</p>
      {:else if $searchQuery.isSuccess}
        <div class:hidden={!opened}>
          <FilterMenu facet={data.stats.facet} />
        </div>
      {/if}
    </div>

    <div class="flex-grow">
      <div class="my-1 flex flex-row items-center justify-between gap-2 px-2 text-sm">
        <select
          class="block rounded-md border border-gray-400 bg-white px-2 py-1"
          bind:value={s}
          on:change={() => {
            const p = $page.url.searchParams;
            p.set("s", s);
            goto(`/problem?${p.toString()}`, { replaceState: false, noScroll: true, invalidateAll: true });
          }}
        >
          {#each selections.entries() as [k, v]}
            <option value={k}>
              {v.label}
            </option>
          {/each}
        </select>

        <div class="w-2/3">
          <SearchBar
            q={$page.url.searchParams.get("q") ?? ""}
            on:search={(e) => {
              const p = new URLSearchParams();
              if (e.detail == null) {
                p.delete("q");
              } else {
                p.set("q", e.detail);
              }
              const s = $page.url.searchParams.get("s");
              if (s != null) {
                p.set("s", s);
              }
              goto(`/problem?${p.toString()}`, { replaceState: false, keepFocus: true, invalidateAll: true });
            }}
          />
        </div>
      </div>

      <div class="mx-2 mb-2 flex flex-row justify-between text-sm">
        <p class="w-full text-right text-gray-700">{data.stats.count}件/{data.stats.total}件 約{data.stats.time}ms</p>
      </div>

      {#if $searchQuery.isLoading}
        <p>Loading...</p>
      {:else if $searchQuery.isError}
        <p>ERROR</p>
      {:else if $searchQuery.isSuccess}
        {#each data.items as item}
          <div class="mx-2 my-0.5 flex flex-col rounded-lg bg-white px-3 py-3 shadow-md shadow-gray-200">
            <div class="flex flex-row items-center justify-between">
              <a href={item.contestUrl} target="_blank" class="block font-medium text-blue-500">
                {item.contestId.toUpperCase()}
              </a>
              <a href={item.problemUrl} target="_blank" class={`block text-pretty font-medium ${textColorStyles.get(item.color ?? "black")}`}>
                {item.problemTitle}
              </a>
              <label class={`text-sm text-black ` + (detail == item.problemId ? "" : "underline")}>
                {detail == item.problemId ? "閉じる" : "詳細"}
                <input
                  type="button"
                  class="h-0 w-0"
                  on:click={() => {
                    detail = detail == item.problemId ? null : item.problemId;
                  }}
                />
              </label>
            </div>
            {#if detail == item.problemId}
              <div class="py-1">
                <div class="my-0.5 flex flex-row items-end justify-between">
                  <span class="block text-sm text-slate-500">{item.contestTitle}</span>
                  <span class={`block rounded-full px-2 py-0.5 text-xs font-medium text-white  ${bgColorStyles.get(item.category)}`}>{item.category}</span>
                </div>
                <div class="flex flex-row items-center justify-between">
                  <span class="block text-sm text-slate-500">{convertDateTime(item.startAt)}</span>
                  {#if item.difficulty != null}
                    <span class={`block rounded-full px-2 py-0.5 text-xs font-medium text-white ${bgColorStyles.get(item.color ?? "black")}`}>{item.difficulty}</span>
                  {/if}
                </div>
              </div>
            {/if}
          </div>
        {/each}
      {/if}
    </div>
  </div>
</div>
