// frontend/src/components/Problem.tsx
import { Item } from "../types/response";
import dayjs from "dayjs";
import timezone from "dayjs/plugin/timezone";
import utc from "dayjs/plugin/utc";
import atcoderLogo from "../assets/atcoder_logo.svg";

dayjs.extend(timezone);
dayjs.extend(utc);

type Props = {
  item: Item;
};

export function Problem({ item }: Props) {
  const startAt = dayjs(item.start_at)
    .tz("Asia/Tokyo")
    .format("YYYY/MM/DD HH:mm:ss");

  const categoryColor = new Map<string, string>([
    ["ABC", "bg-blue-600"],
    ["ABC-Like", "bg-sky-600"],
    ["AGC", "bg-yellow-600"],
    ["AGC-Like", "bg-amber-500"],
    ["AHC", "bg-green-500"],
    ["ARC", "bg-red-500"],
    ["ARC-Like", "bg-orange-700"],
    ["JAG", "bg-slate-500"],
    ["JOI", "bg-slate-600"],
    ["Marathon", "bg-slate-600"],
    ["Other Contests", "bg-slate-600"],
    ["Other Sponsored", "bg-slate-600"],
    ["PAST", "bg-slate-600"],
  ]);

  const difficultyColor = (difficulty: number): string => {
    if (difficulty < 0) {
      return "bg-black";
    } else if (difficulty < 400) {
      return "bg-slate-500";
    } else if (difficulty < 800) {
      return "bg-amber-900";
    } else if (difficulty < 1200) {
      return "bg-green-600";
    } else if (difficulty < 1600) {
      return "bg-sky-600";
    } else if (difficulty < 2000) {
      return "bg-blue-600";
    } else if (difficulty < 2400) {
      return "bg-yellow-600";
    } else if (difficulty < 2800) {
      return "bg-orange-600";
    } else if (difficulty < 3200) {
      return "bg-red-600";
    } else if (difficulty < 3600) {
      return "";
    } else {
      return "";
    }
  };

  return (
    <div className="mx-2 my-5 rounded-2xl bg-slate-200 px-2 py-2 text-gray-900 shadow-sm shadow-slate-700 dark:bg-gray-800 dark:text-slate-100">
      <div className="flex flex-row items-center">
        <img
          alt="AtCoder Logo"
          src={atcoderLogo}
          className="m-2 aspect-square h-12  rounded-full bg-white"
        />
        <div className="mx-2">
          <p className="text-xl">{item.problem_title}</p>
          <a
            href={item.problem_url}
            className="text-sm text-blue-500"
            target="_blank"
            rel="noreferrer"
          >
            {item.problem_url}
          </a>
        </div>
      </div>
      <div className="flex flex-row pt-1">
        <div className="mx-1 rounded-full bg-gray-700 px-2 py-1">{startAt}</div>
        <div
          className={`mx-1 rounded-full ${categoryColor.get(
            item.category
          )} px-2 py-1`}
        >
          {item.category}
        </div>
        <div
          className={`mx-1 rounded-full bg-gray-700 px-2 py-1 ${difficultyColor(
            item.difficulty
          )}`}
        >
          {item.difficulty}
        </div>
      </div>
    </div>
  );
}

// frontend/src/routes/problem/Problem.svelte
<script lang="ts">
  import { bgColorStyles, textColorStyles } from "$lib/colors";
  import type { Problem } from "$lib/response";
  import { createQuery } from "@tanstack/svelte-query";
  import dayjs from "dayjs";
  import timezone from "dayjs/plugin/timezone";
  import utc from "dayjs/plugin/utc";
  import RecommendItem from "./RecommendItem.svelte";
  import { fetchRecommendProblemResult } from "./query";

  dayjs.extend(timezone);
  dayjs.extend(utc);

  export let item: Problem;

  let showDetail: boolean = false;

  $: recommendQuery = createQuery({
    queryKey: [`recommendTo${item.problemId}`, showDetail],
    queryFn: async () => {
      const res = await fetchRecommendProblemResult({ limit: 5, page: 1, problemId: item.problemId }, fetch);
      return res;
    },
    enabled: showDetail,
  });

  function convertDateTime(date: string): string {
    return dayjs(date).tz("Asia/Tokyo").format("YYYY/MM/DD HH:mm:ss");
  }
</script>

<div class="mx-2 my-1 flex flex-col rounded-lg bg-white px-6 py-3 shadow-sm shadow-gray-400">
  <div class="flex flex-row items-center justify-between">
    <a href={item.contestUrl} target="_blank" class="block font-medium text-blue-500">
      {item.contestId.toUpperCase()}
    </a>
    <a href={item.problemUrl} target="_blank" class={`block text-pretty font-medium ${textColorStyles.get(item.color ?? "black")}`}>
      {item.problemTitle}
    </a>
    <label class={`w-12 cursor-pointer text-sm text-black ` + (showDetail ? "" : "underline")}>
      {showDetail ? "閉じる" : "詳細"}
      <input
        type="button"
        class="h-0 w-0"
        on:click={() => {
          showDetail = !showDetail;
        }}
      />
    </label>
  </div>
  {#if showDetail}
    <div class="flex flex-row py-1">
      <div class="my-1 flex flex-grow flex-col items-start justify-between">
        <span class="block text-sm text-slate-500">{item.contestTitle}</span>
        <span class="block text-sm text-slate-500">{convertDateTime(item.startAt)}</span>
      </div>
      <div class="flex flex-col items-end justify-end gap-1">
        <span class={`block rounded-full px-2 py-0.5 text-xs font-medium text-white  ${bgColorStyles.get(item.category)}`}>{item.category}</span>
        {#if item.difficulty != null}
          <span class={`block rounded-full px-2 py-0.5 text-xs font-medium text-white ${bgColorStyles.get(item.color ?? "black")}`}>{item.difficulty}</span>
        {/if}
      </div>
    </div>

    {#if $recommendQuery.isSuccess}
      <p class="mt-2 text-gray-700">似ているかも</p>
      <div class="my-1 flex flex-row gap-4 overflow-x-scroll py-0.5">
        {#each $recommendQuery.data.items as item}
          <RecommendItem {item} />
        {/each}
      </div>
    {/if}
  {/if}
</div>
